//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyclinicHelp.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PolyclinicHelp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CSV | *.csv.
        /// </summary>
        internal static string StartForm_OpenToolStripMenuItem_Click_CSV_____csv {
            get {
                return ResourceManager.GetString("StartForm_OpenToolStripMenuItem_Click_CSV_____csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл пуст.
        /// </summary>
        internal static string StartForm_OpenToolStripMenuItem_Click_Empty_File {
            get {
                return ResourceManager.GetString("StartForm_OpenToolStripMenuItem_Click_Empty_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка чтения файла.
        /// </summary>
        internal static string StartForm_OpenToolStripMenuItem_Click_Error_Reading_File {
            get {
                return ResourceManager.GetString("StartForm_OpenToolStripMenuItem_Click_Error_Reading_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный файл.
        /// </summary>
        internal static string StartForm_OpenToolStripMenuItem_Click_Invalid_File {
            get {
                return ResourceManager.GetString("StartForm_OpenToolStripMenuItem_Click_Invalid_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Входной файл имел неверный формат. Открыть другой файл?.
        /// </summary>
        internal static string StartForm_OpenToolStripMenuItem_Click_Invalid_File__Open_Another {
            get {
                return ResourceManager.GetString("StartForm_OpenToolStripMenuItem_Click_Invalid_File__Open_Another", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл не открыт. Открыть?.
        /// </summary>
        internal static string StartForm_Save_File_Not_Opened__Openь_ {
            get {
                return ResourceManager.GetString("StartForm_Save_File_Not_Opened__Openь_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка сохранения.
        /// </summary>
        internal static string StartForm_Save_Saving_Error {
            get {
                return ResourceManager.GetString("StartForm_Save_Saving_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Таблица CSV | *.csv.
        /// </summary>
        internal static string StartForm_SaveAsToolStripMenuItem_Click_Таблица_CSV_____csv {
            get {
                return ResourceManager.GetString("StartForm_SaveAsToolStripMenuItem_Click_Таблица_CSV_____csv", resourceCulture);
            }
        }
    }
}
